### ISSUE TITLE
友情链接 | 灰鸿个人博客

### ISSUE THREAD

**Issue by huihong3** [huihong3/blog-comments#25]
https://blog.huihongyhy.xyz/link/ 

 灰鸿YHY的个人博客，分享生活与技术，杂谈人世间的琐事，在灰鸿YHY的个人博客记录每一精彩瞬间。

**Comment by huihong3** [comment]
博客名称:
博客链接:
博客描述:
博客头像:(使用http链接)
是否添加本站为友链:

**Comment by ciraos** [comment]
``` yaml
- name: 青葱博客
  link: 'https://ciraos.top/'
  avatar: 'https://cdn.jsdelivr.net/gh/ciraos/greatimgbed@master/avatar.jpg'
  descr: 一切皆付笑谈中
```

已经添加贵站，这是我的链接哦！

**Comment by ciraos** [comment]
博客名称: 青葱博客
博客链接: https://ciraos.top
博客描述: https://cdn.jsdelivr.net/gh/ciraos/greatimgbed@master/avatar.jpg
博客头像:(使用http链接) 一切皆付笑谈中
是否添加本站为友链:  是

**Comment by huihong3** [comment]
> @ciraos
> ``` yaml
> - name: 青葱博客
>   link: 'https://ciraos.top/'
>   avatar: 'https://cdn.jsdelivr.net/gh/ciraos/greatimgbed@master/avatar.jpg'
>   descr: 一切皆付笑谈中
> ```
> 
> 已经添加贵站，这是我的链接哦！

感谢大佬支持，已添加贵站链接

**Comment by xixi-cmd** [comment]
加我一个啊，同志
```yaml
- name: WeiKe_Joe
  link: 'https://chen-shang.top'
  avatar: 'https://cn.chen-shang.top/img/avatar.jpg' 
  descr: Let's go to 2077
```
